# -*- coding: utf-8 -*-
"""Data_Wrangling_for_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQEEDhv_YFAL_xJhcRaRzSlxt7bo2lMw

# DATA WRANGLING FOR SALES PERFORMANCE ANALYSIS USING DATASET
"""

import pandas as pd

df = pd.read_csv("/content/Sales Analysis.csv")

df

columns_to_convert = ['Units Sold', 'Revenue','Cost','Profit']

for column in columns_to_convert:
  df[column]= pd.to_numeric(df[column], errors = 'coerce')

print(df)

df.describe()

df.info()

"""### Convert the date column to datetime format"""

df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')

df

"""### Extract month name and day name"""

df['Month Name'] = df['Date'].dt.month_name()
df['Day Name'] = df['Date'].dt.day_name()
df['Year'] = df['Date'].dt.year

df

"""### Checking null values and removing"""

missing_values = df.isnull().sum()

missing_values

"""# Now data is ready to download"""

if missing_values.sum() == 0:
  df.to_csv('Sales_performance_data.csv', index = False)
  print('The dataset is complete and has been saved')
else:
  print("There are missing values in the dataset.")

df